name: Build PDF in parallel (with log output)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        part: [1, 2, 3, 4, 5, 6] # Define the parts to be processed in parallel
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: cache LaTeX files
        uses: actions/cache@v4
        with:
          path: |
            chapters/*.aux
            hpmor*.aux
            hpmor*.fdb_latexmk
            hpmor*.fls
            hpmor*.out
            hpmor*.pdf
            hpmor*.toc
            hpmor*.xdv
          key: latex

      - name: install requirements
        run: sh scripts/install_requirements_pdf.sh > /dev/null

      - name: make PDF
        run: latexmk hpmor-${{ matrix.part }}

      - name: publish PDF to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: WorkInProgress
          prerelease: true
          files: hpmor-${{ matrix.part }}.pdf
