name: Build PDF all serial
# includes apt update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: caching LaTeX files
        uses: actions/cache@v4
        with:
          path: |
            chapters/*.aux
            hpmor*.aux
            hpmor*.fdb_latexmk
            hpmor*.fls
            hpmor*.out
            hpmor*.pdf
            hpmor*.toc
            hpmor*.xdv
          key: latex

      - name: install requirements
        run: |
          sudo apt update > /dev/null
          sh scripts/install_requirements_pdf.sh > /dev/null

      - name: print versions
        run: |
          cat /etc/os-release
          xelatex -v
          latexmk -v
          # pandoc -v
          python3 --version

      - name: make PDFs
        run: latexmk hpmor-1 hpmor-2 hpmor-3 hpmor-4 hpmor-5 hpmor-6 hpmor > /dev/null

      - name: Publish PDF to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: WorkInProgress
          prerelease: true
          files: hpmor*.pdf
